package com.example.domain.entities

data class PostDetailModel(
    val id: Int? = null,
    val transliterated: String? = null,
    val slug: String? = null,
    val title: String? = null,
    val userId: Int? = null,
    val canonicalUrl: String? = null,
    val contents: String? = null,
    val status: String? = null,
    val moderation: String? = null,
    val promoted: Boolean? = null,
    val clipped: Boolean? = null,
    val points: Int? = null,
    val ratedValue: Int? = null,
    val clipsCount: Int? = null,
    val commentsCount: Int? = null,
    val viewsCount: Int? = null,
    val currentRevision: String? = null,
    val trending: Boolean? = null,
    val seriesId: Int? = null,
    val slideUrl: String? = null,
    val puzzleHashId: String? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val publishedAt: String? = null,
    val lastEditedAt: String? = null,
    val scheduledPublishAt: String? = null,
    val videoId: String? = null,
    val readingTime: Int? = null,
    val canShareSocial: Boolean? = null,
    val license: String? = null,
    val pin: String? = null,
    val summary: String? = null,
    val user: UserModel? = null,
    val htmlContent: String? = null
) : BaseModel() {
}
